version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "rushtong"
    assignees:
      - "rushtong"
    labels:
      - "dependency"
      - "npm"
    commit-message:
      prefix: "dependency"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "rushtong"
    assignees:
      - "rushtong"
    labels:
      - "dependency"
      - "docker"
    commit-message:
      prefix: "dependency"
