version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - "dependency"
      - "npm"
    commit-message:
      prefix: [DUOS-1740] dependency
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - "dependency"
      - "docker"
    commit-message:
      prefix: [DUOS-1740] dependency
