version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "develop"
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - "dependency"
      - "npm"
    commit-message:
      prefix: "[DUOS-1740]"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "develop"
    reviewers:
      - "@DataBiosphere/DUOS"
    labels:
      - "dependency"
      - "docker"
    commit-message:
      prefix: "[DUOS-1740]"
