version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    target-branch: develop
    commit-message:
      prefix: "[DCJ-308-actions]"
    groups:
      action-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependency"
      - "npm"
    commit-message:
      prefix: "[DCJ-308-npm]"
    groups:
      npm-dependencies:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "dependency"
      - "docker"
    commit-message:
      prefix: "[DCJ-308-docker]"
    groups:
      docker-dependencies:
        patterns:
          - "*"
  - commit-message:
      prefix: "[DCJ-308-security]"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
