steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t',
        '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${COMMIT_SHA}',
        '-t',
        '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${SHORT_SHA}',
        '-t',
        '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}',
        '.'
    ]
    timeout: 1200s
images:
  - '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${COMMIT_SHA}'
  - '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}-${SHORT_SHA}'
  - '${_REGISTRY_HOST}/$PROJECT_ID/$REPO_NAME/${_IMAGE}:${BRANCH_NAME}'
tags: # These are CloudBuild tags, not docker image tags
  - '${BRANCH_NAME}-${COMMIT_SHA}'
  - '${BRANCH_NAME}-${SHORT_SHA}'
  - '${BRANCH_NAME}'
substitutions:
  _REGISTRY_HOST: gcr.io # Artifact Registry host
  _IMAGE: duos-ui # Overriden by trigger. eg "argocd-custom-image", "jenkins-gke-deploy"
