# This is an example compose file that can be used for local development.
# Modify the config file in `volumes` to point to the desired environment, default id dev.
#
# Build:
#   docker build . -t duos
# Run:
#   docker-compose up
# Test
#   http://localhost:3000/
version: '3.8'
services:
  app:
    image: duos:latest
    container_name: duos
    ports:
      - 3000:8080
    volumes:
      - ./config/perf.json:/usr/share/nginx/html/config.json
    command: ["nginx", "-g", "daemon off;"]
