version: '3.7'
services:
  app:
    image: duos-ui:latest
    container_name: duos
    ports:
      - 8080:8080
    volumes:
      - ./config/dev.json:/usr/share/nginx/html/config.json
      - ./conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    user: ${CURRENT_UID}
    command: ["nginx", "-g", "daemon off;"]