packages:
  - server

overrides:
  fast-uri@3: ^3.1.4
  fast-uri@4: ^4.1.1

allowBuilds:
  esbuild: false
allowedDeprecatedVersions:
  node-domexception: "1.0.0"
minimumReleaseAgeExclude:
  - find-my-way@9.6.1
