import { div, label, span, h } from 'react-hyperscript-helpers';
import AtAGlance from './AtAGlance';
import ApplicationDownloadLink from '../../components/ApplicationDownloadLink';
import {chunk} from "lodash/fp";

const styles = {
  flexRowElement: {
    fontFamily: 'Montserrat',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    width: '48rem',
  },
  label: {
    fontWeight: 600,
    flex: 1,
    fontSize: '2rem',
  },
  value: {
    fontWeight: 400,
    flex: 2,
    fontSize: '2rem',
  },
  row: {
    width: '80%',
    display: 'flex',
    justifyContent: 'flex-start',
    marginBottom: '5rem',
  },
  title: {
    fontWeight: 800,
    fontSize: '2.7rem',
  },
  subheader: {
    fontWeight: 800,
    fontSize: '2.4rem',
  },
  textBox: {
    marginTop: '1.5rem',
    backgroundColor: 'rgb(237	234	228	)',
    padding: '3rem',
    fontSize: '1.9rem'
  },
  applicantInfoRow: {
    width: '80%',
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '5rem',
  },
};

const generateLabelSpanContents = (labelValue, key,  spanValue, isLoading) => {
  return div(
    {className: 'flex-row-element', style: styles.flexRowElement},
    !isLoading ? [
      label({ className: `${key}-label`, style: styles.label}, [labelValue]),
      span({ className: `${key}-span`, style: styles.value }, [spanValue]),
    ] : [
      div({className: 'text-placeholder', key:`${label}-label-placeholder`, style: {width: '30%', height: '2.4rem', marginBottom: '1.5rem'}}),
      div({className: 'text-placeholder', key:`${label}-text-placeholder`, style: {width: '70%', height: '3.2rem'}}),
    ]
  );
};

// content generated by function
export function DynamicRowGeneration = (rowElementMaxCount, labelArray) => {
  // todo: QUESTION - should I use generateLabelSpanContents before or after chunking?
  // todo: QUESTION - should I apply use this function for the Applicant Information Section as well?
  // todo: what happens when we have an odd number of elements in an array with an even maxRowElementsValue? do we need to generate a blank span?
  //generateLabelSpanContents('', 'row-six-blank', '', false) //blank span to keep row elements in line with those above

  // use the chunk method to organize them in arrays of two
  const chunkedArr = chunk(rowElementMaxCount)(labelArray);

  // use a map function to generate a new array that wraps each chunk in the row style
  // template that you can then plug into the component's return statement
  const output = chunkedArr.map(chunk => {
    return div({className: 'information-row', style: styles.applicantInfoRow}, chunk);
  };

  return output;
};


export default function ApplicationInformation(props) {
  const {
    researcher = '- - ',
    email = '- -',
    department = '- -',
    city = '- -',
    country = '- -',
    institution = '- -',
    pi = '- -',
    piEmail = '- -',
    nonTechSummary,
    isLoading = false,
    collection,
    dataUseBuckets,
    externalCollaborators = [],
    internalCollaborators = [],
    signingOfficial = '- -',
    itDirector = '- -',
    signingOfficialEmail = '- -',
    itDirectorEmail = '- -',
    internalLabStaff = [],
    anvilStorage = '',
    localComputing = '',
    cloudComputing = '',
    cloudProvider,
    cloudProviderDescription
  } = props;

  return (
    div({className: 'application-information-page', style: {padding: '3%', backgroundColor: 'white'}}, [
      !isLoading
        ? h(AtAGlance, {collection: collection, dataUseBuckets: dataUseBuckets, styles: styles})
        : div({className: 'text-placeholder', key: 'application-information-title-placeholder', style: {height: '5rem', width: '20%', marginBottom: '2rem'}}),

      //todo: Applicant Information
      div({className: 'applicant-information-container', style: { margin: '2.5rem 0'}}, [
        div({className: 'applicant-information-subheader', style: styles.title}, ["Applicant Information"]),
        div({className: 'information-row', style: styles.row}, [
          generateLabelSpanContents('Researcher', 'researcher', researcher, isLoading),
          generateLabelSpanContents('Researcher Email', 'researcher-email', email, isLoading),
          generateLabelSpanContents('Department', 'department', department, isLoading)
        ]),
        div({className: 'information-row', style: styles.row}, [
          generateLabelSpanContents('City', 'city', city, isLoading),
          generateLabelSpanContents('Country', 'country', country, isLoading),
          generateLabelSpanContents('Institution', 'institution', institution, isLoading)
        ]),
        div({className: 'information-row', style: styles.row}, [
          generateLabelSpanContents('Principal Investgator', 'principal-investigator', pi, isLoading),
          generateLabelSpanContents('Principal Investigator Email', 'pi-email', piEmail, isLoading),
          generateLabelSpanContents('', 'row-three-blank', '', false) //blank span to keep row elements in line with those above
        ])
      ]),
      !isLoading ? div({className: 'non-technical-summary-subheader', style: styles.title}, ["Non-Technical Summary"])
        : div({className: 'text-placeholder', key: 'non-technical-summary-title-placeholder', style: {height: '4rem', width: '20%', marginBottom: '2rem'}}),
      div({className: 'non-technical-summary-container'}, [
        !isLoading ? div({className: 'non-technical-summary-textbox', style: styles.textBox}, [nonTechSummary])
          : div({className: 'text-placeholder', key: 'non-technical-summary-placeholder', style: { height: '18rem',
            width: '100%',
          }})
      ]),
      div({className: 'application-details-container', style: { margin: '2.5rem 0'}}, [
        div({className: 'applicant-details-subheader', style: styles.title}, ["Application Details"]),
        // figure out what data needs to be visible and save that data in an array
        // using generateLabelSpanContents to generate the value for each element in the array
          // todo: do I include the if logic in here or within the function?
        DynamicRowGeneration(2, [
            generateLabelSpanContents('External Collaborators', 'external-collaborators', externalCollaborators, isLoading),
            generateLabelSpanContents('Internal Collaborators', 'internal-collaborators', internalCollaborators, isLoading),
            generateLabelSpanContents('Signing Official', 'signing-official', signingOfficial, isLoading),
            generateLabelSpanContents('IT Director', 'it-director', itDirector, isLoading),
            generateLabelSpanContents('Signing Official Email', 'signing-official-email', signingOfficialEmail, isLoading),
            generateLabelSpanContents('IT Director Email', 'it-director-email', itDirectorEmail, isLoading),
            generateLabelSpanContents('Internal Lab Staff', 'internal-lab-staff', internalLabStaff, isLoading),
            generateLabelSpanContents('Using AnVIL only for storage and analysis', 'anvil-storage', anvilStorage, isLoading),
            generateLabelSpanContents('Requesting Permission to use local computing', 'local-computing', localComputing, isLoading),
            generateLabelSpanContents('Requesting permission to use cloud computing', 'cloud-computing', cloudComputing, isLoading),
            generateLabelSpanContents('Cloud Provider (description below)', 'cloud-provider', cloudProvider, isLoading)
        ]),
        // // do not display this first row at all if there is no data to show
        // (externalCollaborators.length>0 || internalCollaborators.length>0) ?
        //   div({className: 'information-row', style: styles.applicantInfoRow}, [
        //     (externalCollaborators.length>0) ?
        //       generateLabelSpanContents('External Collaborators', 'external-collaborators', externalCollaborators, isLoading)
        //       : generateLabelSpanContents('', 'row-one-blank', '', false), //blank span to keep row elements in line with those above
        //     (internalCollaborators.length>0) ?
        //       generateLabelSpanContents('Internal Collaborators', 'internal-collaborators', internalCollaborators, isLoading)
        //       : generateLabelSpanContents('', 'row-one-blank', '', false), //blank span to keep row elements in line with those above
        //   ]) : '',
        // div({className: 'information-row', style: styles.applicantInfoRow}, [
        //   generateLabelSpanContents('Signing Official', 'signing-official', signingOfficial, isLoading),
        //   generateLabelSpanContents('IT Director', 'it-director', itDirector, isLoading)
        // ]),
        // div({className: 'information-row', style: styles.applicantInfoRow}, [
        //   generateLabelSpanContents('Signing Official Email', 'signing-official-email', signingOfficialEmail, isLoading),
        //   generateLabelSpanContents('IT Director Email', 'it-director-email', itDirectorEmail, isLoading),
        // ]),
        // (internalCollaborators.length>0 || anvilStorage) ?
        //   div({className: 'information-row', style: styles.applicantInfoRow}, [
        //     ( internalCollaborators.length>0) ?
        //       generateLabelSpanContents('Internal Lab Staff', 'internal-lab-staff', internalLabStaff, isLoading)
        //       : generateLabelSpanContents('', 'row-four-blank', '', false), //blank span to keep row elements in line with those above
        //     (anvilStorage) ?
        //       generateLabelSpanContents('Using AnVIL only for storage and analysis', 'anvil-storage', anvilStorage, isLoading)
        //       : generateLabelSpanContents('', 'row-four-blank', '', false), //blank span to keep row elements in line with those above
        //   ]) : '',
        // div({className: 'information-row', style: styles.applicantInfoRow}, [
        //   generateLabelSpanContents('Requesting Permission to use local computing', 'local-computing', localComputing, isLoading),
        //   generateLabelSpanContents('Requesting permission to use cloud computing', 'cloud-computing', cloudComputing, isLoading),
        // ]),
        // (cloudComputing) ? div({className: 'information-row', style: styles.applicantInfoRow}, [
        //   generateLabelSpanContents('Cloud Provider (description below)', 'cloud-provider', cloudProvider, isLoading),
        //   generateLabelSpanContents('', 'row-six-blank', '', false) //blank span to keep row elements in line with those above
        // ]) : '',
        (cloudComputing) ? div({className: 'cloud-provider-description-container'}, [
          !isLoading ? div({className: 'cloud-provider-description-textbox', style: styles.textBox}, [cloudProviderDescription])
            : div({className: 'text-placeholder', key: 'cloud-provider-description-placeholder', style: { height: '18rem',
              width: '100%',
            }})
        ])  : ''
      ]),
    ])
  );
}

