export const Models = {
  dac: {
    dacId: null,
    name: '',
    description: '',
    createDate: null,
    updateDate: null,
    chairpersons: [],
    members: []
  },
  dar: {
    researcherProperties: [],
    researcherId: '',
    rus: '',
    status: '',
    hasAdminComment: false,
    adminComment: '',
    hasPurposeStatements: false,
    darCode: '',
    projectTitle: '',
    purposeStatements: [],
    hasDiseases: false,
    diseases: [],
    researchType: [],
    researchTypeManualReview: '',
    pi: '',
    havePI: false,
    profileName: '',
    institution: '',
    department: '',
    city: '',
    country: '',
    datasets: [],
    structuredRp: '',
    structuredLimitations: '',
    dataUse: {
      diseases: false,
      methods: false,
      controls: false,
      population: false,
      other: false,
      otherText: "",
      forProfit: false,
      oneGender: false,
      gender: null,
      pediatric: false,
      illegalbehave: false,
      addiction: false,
      sexualdiseases: false,
      stigmatizediseases: false,
      vulnerablepop: false,
      popmigration: false,
      psychtraits: false,
      nothealth: false
    }
  },
  error: { show: false, title: '', msg: [''] }
};
