on: [pull_request]
name: cypress component tests
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Log Actor
        run: echo "${{ github.actor }}"
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM Install
        run: npm ci
      - name: Cypress info
        run: npx cypress info
      - name : Cypress run component tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: chrome
