on: [pull_request]
name: cypress tests
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Log Actor
        run: echo "${{ github.actor }}"

      # For all dependabot PRs, add a sleep time from 0-9 minutes to reduce
      # the contention on pulling repo secrets from multiple, simultaneous PRs
      - name: Calculate Sleep if Dependabot
        id: sleep
        if: github.actor == 'dependabot[bot]'
        shell: bash
        run: echo "::set-output name=minutes::$(($GITHUB_RUN_NUMBER % 10))"
      - name: Sleep if Dependabot
        if: github.actor == 'dependabot[bot]'
        uses: whatnick/wait-action@master
        with:
          time: '${{ steps.sleep.outputs.minutes }}m'

      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Install
        run: npm ci
      - name: Copy Configs
        run: cp config/dev.json public/config.json
      - name: NPM Build
        run: CI=false npm run build --silent
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_ADMIN: ${{ secrets.DUOS_AUTOMATION_ADMIN }}
          CYPRESS_CHAIR: ${{ secrets.DUOS_AUTOMATION_CHAIR }}
          CYPRESS_MEMBER: ${{ secrets.DUOS_AUTOMATION_MEMBER }}
          CYPRESS_RESEARCHER: ${{ secrets.DUOS_AUTOMATION_RESEARCHER }}
          CYPRESS_SIGNING_OFFICIAL: ${{ secrets.DUOS_AUTOMATION_SIGNING_OFFICIAL }}
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
