on: [pull_request]
name: docker build
jobs:
  scan:
    name: docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker build .
