on: [pull_request]
name: Lint Changed Files
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Extract Node.js version
        run: echo "NODE_VERSION=$(sed -n 's/FROM node:\([0-9.]*\).*/\1/p' Dockerfile)" >> $GITHUB_ENV
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Lint changed files
        run: npx eslint
        env:
          DESTINATION_REF: ${{ github.event.pull_request.base.ref }}
      - name: TypeScript check
        run: npx tsc --noEmit
        env:
          DESTINATION_REF: ${{ github.event.pull_request.base.ref }}
