on: [pull_request]
name: npm audit
jobs:
  scan:
    name: minnie-kenny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'broadinstitute/minnie-kenny'
          path: 'minnie-kenny'
      - uses: DamianReeves/write-file-action
        with:
          path: ./.git/minnie-kenny.gitconfig
          contents: |
            echo "[secrets]
                providers = git secrets --aws-provider
                patterns = (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}
                patterns = (\"|')?(AWS|aws|Aws)?_?(SECRET|secret|Secret)?_?(ACCESS|access|Access)?_?(KEY|key|Key)(\"|')?\\s*(:|=>|=)\\s*(\"|')?[A-Za-z0-9/\\+=]{40}(\"|')?
                patterns = (\"|')?(AWS|aws|Aws)?_?(ACCOUNT|account|Account)_?(ID|id|Id)?(\"|')?\\s*(:|=>|=)\\s*(\"|')?[0-9]{4}\\-?[0-9]{4}\\-?[0-9]{4}(\"|')?
                allowed = AKIAIOSFODNN7EXAMPLE
                allowed = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
          write-mode: overwrite
      - name: copy
        run: |
          cp minnie-kenny/minnie-kenny.sh .
      - name: check install
        run: |
          ls -al .
          ls -al minnie-kenny
          ls -al .git
