on: [pull_request]
name: npx audit-ci
jobs:
  scan:
    name: npx audit-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: npx audit-ci
        run: npx audit-ci --moderate --config config/audit-ci.json
