on: [pull_request]
name: npm audit
jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: npx audit
        run: npx audit-ci --moderate
