on: [pull_request]
name: npm audit
jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.5.2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
