on: [pull_request]
name: Trivy
jobs:
  build:
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: broadinstitute/dsp-appsec-trivy-action@v1
