on: [pull_request]
name: Trivy
jobs:
  build:
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - uses: broadinstitute/dsp-appsec-trivy-action@v1
      - run: |
          docker build -f Dockerfile -t docker.io/broadinstitute/duos:${{ github.sha }} .
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/broadinstitute/duos:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL'
